### Get sorting results
GET http://127.0.0.1:5000/results

### Add a new sorting result
POST http://127.0.0.1:5000/results
Content-Type: application/json

{
    "year": 2024,
    "plastics": 30,
    "paper": 10,
    "metals": 7
}

### Add a new history record
POST http://127.0.0.1:5000/history
Content-Type: application/json

{
    "year": 2024,
    "plastics": 30,
    "paper": 10,
    "metals": 7
}
